[project]
name = "03-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.14.2",
    "minsearch>=0.0.7",
    "requests>=2.32.5",
]
